// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Module3Prototype.Data;

namespace Module3Prototype.Migrations
{
    [DbContext(typeof(Module3PrototypeContext))]
    partial class Module3PrototypeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Module3Prototype.Models.Module", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CentralModulation")
                        .HasColumnType("int");

                    b.Property<int>("LocalStimulation")
                        .HasColumnType("int");

                    b.Property<int>("RegionalInfluences")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Module");
                });
#pragma warning restore 612, 618
        }
    }
}
